### ISSUE TITLE
Old json_schema_generator on PyPI doesn't work with Python 3

### ISSUE THREAD

**Issue by tdhopper** [scrapinghub/skinfer#10]
When I try to run under Python3 after installing with Pip, I get 

```
Traceback (most recent call last):
  File "/bin/skinfer", line 9, in <module>
    from skinfer import schema_inferer
  File "/lib/python3.5/site-packages/skinfer/__init__.py", line 36, in <module>
    from .schema_inferer import generate_schema_for_sample as generate_schema  # NOQA
  File "/lib/python3.5/site-packages/skinfer/schema_inferer.py", line 5, in <module>
    from skinfer.draft4_generator import JsonSchemaGenerator
  File "/lib/python3.5/site-packages/skinfer/draft4_generator.py", line 5, in <module>
    import json_schema_generator
  File "/lib/python3.5/site-packages/json_schema_generator/__init__.py", line 1, in <module>
    from .generator import *
  File "/lib/python3.5/site-packages/json_schema_generator/generator.py", line 4, in <module>
    from .schema_types import Type, ObjectType, ArrayType
  File "/lib/python3.5/site-packages/json_schema_generator/schema_types.py", line 60, in <module>
    types.NoneType: NullType,
AttributeError: module 'types' has no attribute 'NoneType'
```

It seems that is because the json_schema_generator on PyPI doesn't have [this fix](https://github.com/perenecabuto/json_schema_generator/blob/08139c3f89f6b890825a8249ed17bb412a49639d/json_schema_generator/schema_types.py#L59-L82) for Python 3.

**Comment by tdhopper** [comment]
This works for now: git+git://github.com/perenecabuto/json_schema_generator.git

**Comment by eliasdorneles** [comment]
Hey @tdhopper -- yeah, I've opened an issue there some time ago for the PyPI release: https://github.com/perenecabuto/json_schema_generator/issues/13

I haven't heard from the maintainer yet, I'm starting to consider ditching (or bundling) the dependency.

**Comment by tdhopper** [comment]
OK. 

Even with the dependency working, it looks like [`sys.maxint`](https://github.com/scrapinghub/skinfer/blob/4de89a5868d1c2b7e71337a8dc1681f8ec86c783/skinfer/json_schema_merger.py#L61) prevents this from running on python3.

**Comment by Trolldemorted** [comment]
@tdhopper did you manage to get skinfer to run on python3?

**Comment by tdhopper** [comment]
@Trolldemorted No
